<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>Retro.Debug.Data.Provider</PackageId>
    <Title>Retro Debug Data Provider</Title>
    <Description>This project goal is to provide as much debugging support as possible for retro assembler starting with Kick Assembler.</Description>
    <PackageTags>KickAssembler;retro;c64</PackageTags>
    <Authors>Miha Markic</Authors>
    <Owners>Miha Markic</Owners>
    <Version>0.3.0-alpha</Version>
    <RepositoryUrl>https://github.com/MihaMarkic/Retro-debug-data-provider</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/MihaMarkic/Retro-debug-data-provider</PackageProjectUrl>
    <PackageReleaseNotes>See https://github.com/MihaMarkic/Retro-debug-data-provider/blob/main/CHANGES.md</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <ImplicitUsings>enable</ImplicitUsings>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>CS1658,CS1584</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.Collections.Immutable" />
  </ItemGroup>
  <Choose>
    <When Condition=" '$(Configuration)'=='Release' ">
      <PropertyGroup>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
      </PropertyGroup>
      <ItemGroup>
        <None Include="..\..\..\README.md" Pack="true" PackagePath="\">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Retro.Debug.Data.Provider.props" Pack="true" PackagePath="\build">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
      </ItemGroup>
    </When>
  </Choose>

  <Target Name="InjectPackageReleaseNotesFromFile" BeforeTargets="GenerateNuspec" Condition=" '$(Configuration)'=='Release' ">
    <PropertyGroup>
      <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)../../../../CHANGELOG.md"))</PackageReleaseNotes>
    </PropertyGroup>
  </Target>

  <ItemGroup>
    <None Update="binaries\KickAss\KickAss.cfg" Pack="true" PackagePath="\content">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="binaries\KickAss\KickAss.jar" Pack="true" PackagePath="\content">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
<!--    <None Include="binaries\KickAss\KickAss.cfg" Pack="true" PackagePath="\KickAssembler" />-->
<!--    <None Include="binaries\KickAss\KickAss.jar" Pack="true" PackagePath="\KickAssembler" />-->
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(AssemblyName).Test</_Parameter1>
      <!-- We use the value of AssemblyName to declare the value of the attribute -->
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="KickAssembler\Grammar\gen\Righthand\RetroDbgDataProvider\KickAssembler\" />
  </ItemGroup>
</Project>
